[server]
host = "192.168.2.101"
port = 3000
pidfile = "/home/richard/.terrazzo/terminal-3000.pid"
private_root_ca = "/home/richard/.terrazzo/root_ca"
token_lifetime = "15m 5s"
token_refresh = "14m 50s"

[server.password]
hash = "bRZZiFMRd/RBn7hW3sgl+WTPSh4"
iterations = 60000
salt = "sdfVZP9WQXeC9eyBn3jUWA"

[letsencrypt]
environment = "Staging"
contact = "mailto:info@pavy.one"
domain = "munich.pavy.one"

[letsencrypt.credentials]
id = "https://acme-staging-v02.api.letsencrypt.org/acme/acct/201888134"
key_pkcs8 = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgGwnyeaL9VNaDZAh66yXAPYxDTayA4-cY6PVeOt9m5IGhRANCAATddugm9jN1EYcKsUhRjqoEvVLpoRmO_ENSFGrIZ219gppip5o4QqN1zWqnGaSp3j3zcgOeHSZMOqbzY_RBsbJp"
directory = "https://acme-staging-v02.api.letsencrypt.org/directory"

[letsencrypt.certificate]
certificate = """
-----BEGIN CERTIFICATE-----
MIIDxTCCA0ugAwIBAgISLIjHq5NhRgfTrEeNXHpD9xLOMAoGCCqGSM49BAMDMFIx
CzAJBgNVBAYTAlVTMSAwHgYDVQQKExcoU1RBR0lORykgTGV0J3MgRW5jcnlwdDEh
MB8GA1UEAxMYKFNUQUdJTkcpIFBzZXVkbyBQbHVtIEU1MB4XDTI1MDUyNTA1MTQ1
N1oXDTI1MDgyMzA1MTQ1NlowGjEYMBYGA1UEAxMPbXVuaWNoLnBhdnkub25lMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY9y7zsvCG/28ZxO4vI1Rm770TALQ5oYZ
w9KioisdSuhqJTARwFc+UEeTC3agVM5XOGgr6Q7lyczpyn511eIYg6OCAjcwggIz
MA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU5qV+hS7Y2G/inCrqnIowtNNFpcgwHwYD
VR0jBBgwFoAU/EbRAUNfu3umPTBorhG64LxtydMwNgYIKwYBBQUHAQEEKjAoMCYG
CCsGAQUFBzAChhpodHRwOi8vc3RnLWU1LmkubGVuY3Iub3JnLzAaBgNVHREEEzAR
gg9tdW5pY2gucGF2eS5vbmUwEwYDVR0gBAwwCjAIBgZngQwBAgEwMQYDVR0fBCow
KDAmoCSgIoYgaHR0cDovL3N0Zy1lNS5jLmxlbmNyLm9yZy83OS5jcmwwggEWBgor
BgEEAdZ5AgQCBIIBBgSCAQIBAAB/AOT7d0ohJMWGQLGDL1Cr+tyEo4rtcZHutmki
N5LL9iiRAAABlwYTJcoACAAABQABAHqSBAMASDBGAiEAw/czpX59fXo8jBkJJoZ6
S+1n74xpFx8csaSJ2vP+e18CIQD/F6YCZz4UZgDe2yGbuI9gvMUxoEfn+Bq66va5
ZXep0gB9AMBdIFQ4XLLPsheSDS8Nx4NSYUexqk/vl8p44fC7hPztAAABlwYTJzMA
CAAABQAfHRohBAMARjBEAiB0sK3S5zBf7N4wmYOTBpH09mNaGbVBU0qLTcNXD5F9
SQIgOTKRNut2y7FBqk4xqnf7b0CkQGiWxtcKPx+0nKzJOlkwCgYIKoZIzj0EAwMD
aAAwZQIwSDzpQ949oEJ66f+hWBF7L7VxffPy2Xmrzaf/NZRXRSyYXPD4FJBUnFro
dWuC00BsAjEAjltkL+CKn7tT4nLUbv6ky9DXOmzbVcwR6GwqkGv/xT7VX9nIOQBv
Cc/z/n2C/jfI
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEljCCAn6gAwIBAgIQRzEp1D1mDiVVv4b1zlB56jANBgkqhkiG9w0BAQsFADBm
MQswCQYDVQQGEwJVUzEzMDEGA1UEChMqKFNUQUdJTkcpIEludGVybmV0IFNlY3Vy
aXR5IFJlc2VhcmNoIEdyb3VwMSIwIAYDVQQDExkoU1RBR0lORykgUHJldGVuZCBQ
ZWFyIFgxMB4XDTI0MDMxMzAwMDAwMFoXDTI3MDMxMjIzNTk1OVowUjELMAkGA1UE
BhMCVVMxIDAeBgNVBAoTFyhTVEFHSU5HKSBMZXQncyBFbmNyeXB0MSEwHwYDVQQD
ExgoU1RBR0lORykgUHNldWRvIFBsdW0gRTUwdjAQBgcqhkjOPQIBBgUrgQQAIgNi
AATljbbcV+mqWZa3g+z0bDOuBpZOtbi48iK9rjLtPdRU0WsgVp53MW3nXFU6qVYV
zEYaYd6PSmec0Tj3R5zEp5/F+cuOjTdh3AkTMzYm1tkflocPBN5APHYZ+76WxZad
q+WjggEAMIH9MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
KwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU/EbRAUNfu3um
PTBorhG64LxtydMwHwYDVR0jBBgwFoAUtfNl8v6wCpIf+zx980SgrGMlwxQwNgYI
KwYBBQUHAQEEKjAoMCYGCCsGAQUFBzAChhpodHRwOi8vc3RnLXgxLmkubGVuY3Iu
b3JnLzATBgNVHSAEDDAKMAgGBmeBDAECATArBgNVHR8EJDAiMCCgHqAchhpodHRw
Oi8vc3RnLXgxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAAtCGn4iG
cupruhkCTcoDqSIVTFgVR8JJ3GvGL7SYwIc4Fn0As66nQgnkATIzF5+gFb+CXEQD
qR2Jo+R38OeT7lQ1rNDcaJcbY6hL8cNRku3QlcfdYODZ5pgTVH04gTZUJISZKLjD
kMMcQIDZlF7iYqTvmHbn2ISSKorsJ3QKAvWhHwMoJtocSz3VeDJIep5QtbHnoXh1
/dyDx7sp8RuhC0eO9ElTgDtiA2V6JxigLPzqcnibBBR4bFLGtMNE4EvOOD/Fkd0L
hdGDbAMNd+O06n+b0rgmDvg75IgOV6fpDrdZFoiNfCckOEJh9v10uYt4pTc3B6lf
zI/X3EWP1H4VJmsYuy+OA29jPeP831sAObZtd3RWv0LQPrMfx6FCmy4AaeYEMvul
FrF6OX+JbssE+bn83F+sGEMZu/eVBwwKh3db7+2UduMdTOb8DePE3Aqlg9zofS8X
9fJXrrp+PPrdQyvM3e8DxuioWa9GLG30yD9WD6WTlSiiOrdWGOzisWpW4shFoL8u
0EfmeLVU4JVbauhOYZASQXABNeXewe9lqJWwfqaARYpRjyf+jRibn22H5NVK4Vog
l55Iq1rUgjc8r493NaNrlNwG7va7Ztkch5lJ3oL/FEVlVSK4snTbgb0b5qjQz3SA
i7rA/8QRZvOLnKNtdEUlDZNrzkZwHNluLGw=
-----END CERTIFICATE-----
"""
private_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg/7nWYcmc0huzTsCX
ps8X7ZA8xqx5Ur3eLJX9ig2smFyhRANCAARj3LvOy8Ib/bxnE7i8jVGbvvRMAtDm
hhnD0qKiKx1K6GolMBHAVz5QR5MLdqBUzlc4aCvpDuXJzOnKfnXV4hiD
-----END PRIVATE KEY-----
"""
