name: Check
runs:
  using: "composite"

  steps:
    - name: Stylance terminal
      run: cd terminal && stylance .
      shell: bash

    - name: Stylance game
      run: cd game && stylance .
      shell: bash

    - name: Check
      run: |
        cargo check --locked --no-default-features --features max-level-debug,diagnostics,client-all,server-all
        cargo check --locked --bin terrazzo-terminal --no-default-features --features server-all --features max-level-debug,diagnostics
        cargo check --locked --bin terrazzo-terminal --no-default-features --features server-all --features max-level-info
        cargo check --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features terminal-server
        cargo check --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features text-editor-server
        cargo check --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features converter-server
        cargo check --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features port-forward-server
        cargo check --locked --bin game --no-default-features --features server,max-level-debug,debug,diagnostics
        cargo check --locked --bin game --no-default-features --features server,max-level-info --release
      shell: bash

    - name: Clippy
      run: |
        cargo clippy --locked --no-default-features --features max-level-debug,diagnostics,client-all,server-all
        cargo clippy --locked --bin terrazzo-terminal --no-default-features --features server-all --features max-level-debug,diagnostics
        cargo clippy --locked --bin terrazzo-terminal --no-default-features --features server-all --features max-level-info
        cargo clippy --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features terminal-server
        cargo clippy --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features text-editor-server
        cargo clippy --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features converter-server
        cargo clippy --locked --bin terrazzo-terminal --no-default-features --features max-level-debug,debug,diagnostics --features port-forward-server
        cargo clippy --locked --bin game --no-default-features --features server,max-level-debug,debug,diagnostics
        cargo clippy --locked --bin game --no-default-features --features server,max-level-info --release
      shell: bash

    - name: Rustfmt
      run: cargo fmt
      shell: bash

    - name: Documentation
      run: cargo doc --locked --all-features
      shell: bash
