name: Check
runs:
  using: "composite"

  steps:
    - name: Stylance terrazzo-terminal
      run: cd terrazzo-terminal && stylance .
      shell: bash

    - name: Stylance game
      run: cd game && stylance .
      shell: bash

    - name: Clippy
      run: |
        cargo clippy --no-default-features --features client,max_level_debug
        cargo clippy --no-default-features --features client,max_level_info
        cargo clippy --bin game --no-default-features --features server,max_level_debug
        cargo clippy --bin game --no-default-features --features server,max_level_info
        cargo clippy --bin terrazzo-terminal --no-default-features --features server,max_level_debug
        cargo clippy --bin terrazzo-terminal --no-default-features --features server,max_level_info
      shell: bash

    - name: Rustfmt
      run: cargo fmt
      shell: bash

    - name: Documentation
      run: cargo doc --all-features
      shell: bash
