name: Publish
runs:
  using: "composite"
  steps:
    - name: Login
      run: cargo login --locked $CRATES_TOKEN
      shell: bash
    - name: Publish
      run: |
        cargo publish --locked -p terrazzo-pty
        cargo publish --locked -p terrazzo-terminal
      shell: bash
