name: Publish (dry-run)
runs:
  using: "composite"
  steps:
    - name: Publish (dry-run)
      run: |
        cargo publish -p terrazzo-pty --dry-run
        cargo publish -p terrazzo-terminal --dry-run
      shell: bash
